spring:
  application:
    name: todo-app
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
    url: "jdbc:mysql://localhost:3306/test"
  mysql:
    console:
      enabled: true
      path: /mysql-console
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update